In [128]:
import numpy as np
import pandas as pd


In [159]:
initial_train_df = pd.read_csv("train.csv")


**Checking all the columns which have Null values**

In [160]:
initial_train_df.columns[pd.isnull(initial_train_df).any()]
#pd.isnull(initial_train_df)

Index([u'Age', u'Cabin', u'Embarked'], dtype='object')

**Checking unique column values**

In [161]:
initial_train_df.Cabin.unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6', 'C23 C25 C27',
       'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33', 'F G73', 'E31',
       'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101', 'F E69', 'D47',
       'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4', 'A32', 'B4',
       'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35', 'C87', 'B77',
       'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19', 'B49', 'D',
       'C22 C26', 'C106', 'C65', 'E36', 'C54', 'B57 B59 B63 B66', 'C7',
       'E34', 'C32', 'B18', 'C124', 'C91', 'E40', 'T', 'C128', 'D37',
       'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44', 'A34', 'C104', 'C111',
       'C92', 'E38', 'D21', 'E12', 'E63', 'A14', 'B37', 'C30', 'D20',
       'B79', 'E25', 'D46', 'B73', 'C95', 'B38', 'B39', 'B22', 'C86',
       'C70', 'A16', 'C101', 'C68', 'A10', 'E68', 'B41', 'A20', 'D19',
       'D50', 'D9', 'A23', 'B50', 'A26', 'D48', 'E58', 'C126', 'B71',
       'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63', 'C62 C64', 'E24',

In [201]:
initial_train_df.columns
selected_features_df = initial_train_df[['Pclass', 'Sex', 'Age', 'Parch','SibSp','Embarked', 'Fare', 'Survived']]
#missing_age_rows = float(len(selected_features_df[pd.isnull(selected_features_df['Age'])]))
#len(selected_features_df)
# selected_features_df = selected_features_df.dropna(subset=['Age'],how='any',axis = 0)
median_age = selected_features_df['Age'].dropna().median()
mode_embarked = selected_features_df['Embarked'].dropna().mode().values
# print mode_embarked
selected_features_df.loc[ (selected_features_df.Age.isnull()), 'Age'] = median_age
selected_features_df.loc[ (selected_features_df.Embarked.isnull()), 'Embarked'] = mode_embarked




selected_features_df.columns[pd.isnull(selected_features_df).any()]


Ports = list(enumerate(np.unique(selected_features_df['Embarked'])))    # determine all values of Embarked,
Ports_dict = { name : i for i, name in Ports }              # set up a dictionary in the form  Ports : index
selected_features_df.Embarked = selected_features_df.Embarked.map( lambda x: Ports_dict[x]).astype(int)     # Convert all Embark strings to int

selected_features_df

Pclass     Sex  Age  Parch  SibSp  Embarked      Fare  Survived
0         3    male   22      0      1         2    7.2500         0
1         1  female   38      0      1         0   71.2833         1
2         3  female   26      0      0         2    7.9250         1
3         1  female   35      0      1         2   53.1000         1
4         3    male   35      0      0         2    8.0500         0
5         3    male   28      0      0         1    8.4583         0
6         1    male   54      0      0         2   51.8625         0
7         3    male    2      1      3         2   21.0750         0
8         3  female   27      2      0         2   11.1333         1
9         2  female   14      0      1         0   30.0708         1
10        3  female    4      1      1         2   16.7000         1
11        1  female   58      0      0         2   26.5500         1
12        3    male   20      0      0         2    8.0500         0
13        3    male   39      5      1         2   31.2750         0
14        3  female   14      0      0         2    7.8542         0
15        2  female   55      0      0         2   16.0000         1
16        3    male    2      1      4         1   29.1250         0
17        2    male   28      0      0         2   13.0000         1
18        3  female   31      0      1         2   18.0000         0
19        3  female   28      0      0         0    7.2250         1
20        2    male   35      0      0         2   26.0000         0
21        2    male   34      0      0         2   13.0000         1
22        3  female   15      0      0         1    8.0292         1
23        1    male   28      0      0         2   35.5000         1
24        3  female    8      1      3         2   21.0750         0
25        3  female   38      5      1         2   31.3875         1
26        3    male   28      0      0         0    7.2250         0
27        1    male   19      2      3         2  263.0000         0
28        3  female   28      0      0         1    7.8792         1
29        3    male   28      0      0         2    7.8958         0
..      ...     ...  ...    ...    ...       ...       ...       ...
861       2    male   21      0      1         2   11.5000         0
862       1  female   48      0      0         2   25.9292         1
863       3  female   28      2      8         2   69.5500         0
864       2    male   24      0      0         2   13.0000         0
865       2  female   42      0      0         2   13.0000         1
866       2  female   27      0      1         0   13.8583         1
867       1    male   31      0      0         2   50.4958         0
868       3    male   28      0      0         2    9.5000         0
869       3    male    4      1      1         2   11.1333         1
870       3    male   26      0      0         2    7.8958         0
871       1  female   47      1      1         2   52.5542         1
872       1    male   33      0      0         2    5.0000         0
873       3    male   47      0      0         2    9.0000         0
874       2  female   28      0      1         0   24.0000         1
875       3  female   15      0      0         0    7.2250         1
876       3    male   20      0      0         2    9.8458         0
877       3    male   19      0      0         2    7.8958         0
878       3    male   28      0      0         2    7.8958         0
879       1  female   56      1      0         0   83.1583         1
880       2  female   25      1      0         2   26.0000         1
881       3    male   33      0      0         2    7.8958         0
882       3  female   22      0      0         2   10.5167         0
883       2    male   28      0      0         2   10.5000         0
884       3    male   25      0      0         2    7.0500         0
885       3  female   39      5      0         1   29.1250         0
886       2    male   27      0      0         2   13.0000         0
887


**One hot encoding**

In [195]:
selected_features_df['Gender'] = selected_features_df['Sex'].map( {'female': 0, 'male': 1} ).astype(int)

#df_train = pd.get_dummies(selected_features_df, columns = ['Sex'])
selected_features_df = selected_features_df.drop(['Sex'],axis=1)
selected_features_df
df_train = selected_features_df

/home/makala/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [196]:
predictors = list(df_train.columns)
predictors.remove('Survived')
predictors
x = df_train[predictors].values
y = list(df_train['Survived'].values)
x,y

(array([[  3.    ,  22.    ,   0.    , ...,   2.    ,   7.25  ,   1.    ],
        [  1.    ,  38.    ,   0.    , ...,   0.    ,  71.2833,   0.    ],
        [  3.    ,  26.    ,   0.    , ...,   2.    ,   7.925 ,   0.    ],
        ..., 
        [  3.    ,  28.    ,   2.    , ...,   2.    ,  23.45  ,   0.    ],
        [  1.    ,  26.    ,   0.    , ...,   0.    ,  30.    ,   1.    ],
        [  3.    ,  32.    ,   0.    , ...,   1.    ,   7.75  ,   1.    ]]),
 [0,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  1,
  1,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,

In [166]:
from sklearn import cross_validation
from sklearn.ensemble import RandomForestClassifier

max_score = 0
max_estimators = 0
for i in range(160,191,5):
    alg = RandomForestClassifier(n_estimators = i, max_features = None, warm_start = True)
    scores = cross_validation.cross_val_score(alg,x,y,cv=10)
    print i,"The cross validation accuracy is ", scores.mean()
    if scores.mean() > max_score:
        max_score = scores.mean()
        max_estimators = i
max_estimators

160 The cross validation accuracy is  0.803716660992
165 The cross validation accuracy is  0.804877709681
170 The cross validation accuracy is  0.808211043014
175 The cross validation accuracy is  0.807124900692
180 The cross validation accuracy is  0.813841504937
185 The cross validation accuracy is  0.80490267847
190 The cross validation accuracy is  0.80819855862


180

In [143]:
test_df.columns
max_estimators

300

In [197]:
test_df = pd.read_csv("test.csv")
p_ids = test_df['PassengerId']
test_df = test_df[['Pclass', 'Sex', 'Age', 'Parch','SibSp','Embarked', 'Fare']]

test_median_age = test_df['Age'].dropna().median()
test_mode_embarked = test_df['Embarked'].dropna().mode().values[0]


test_df.loc[ (test_df.Age.isnull()), 'Age'] = test_median_age
test_df.loc[ (test_df.Embarked.isnull()), 'Embarked'] = test_mode_embarked


test_df.Embarked = test_df.Embarked.map( lambda x: Ports_dict[x]).astype(int) 
test_df['Gender'] = test_df['Sex'].map( {'female': 0, 'male': 1} ).astype(int)
test_df = test_df.drop(['Sex'],axis=1)

#test_df = pd.get_dummies(test_df, columns = ['Sex'])
if len(test_df.Fare[ test_df.Fare.isnull() ]) > 0:
    median_fare = np.zeros(3)
    for f in range(0,3):                                              # loop 0 to 2
        median_fare[f] = test_df[ test_df.Pclass == f+1 ]['Fare'].dropna().median()
    for f in range(0,3):                                              # loop 0 to 2
        test_df.loc[ (test_df.Fare.isnull()) & (test_df.Pclass == f+1 ), 'Fare'] = median_fare[f]
print test_df.columns[pd.isnull(test_df).any()]

Index([], dtype='object')


In [198]:
alg = RandomForestClassifier(n_estimators = 100, max_features = None, warm_start = True)
alg.fit(x,y)
test_pred = alg.predict_proba(test_df)
test_pred

array([[ 0.9       ,  0.1       ],
       [ 0.89      ,  0.11      ],
       [ 0.4       ,  0.6       ],
       [ 0.25      ,  0.75      ],
       [ 0.47      ,  0.53      ],
       [ 0.9425    ,  0.0575    ],
       [ 0.91333333,  0.08666667],
       [ 0.91      ,  0.09      ],
       [ 0.06      ,  0.94      ],
       [ 0.96      ,  0.04      ],
       [ 0.88      ,  0.12      ],
       [ 0.93      ,  0.07      ],
       [ 0.        ,  1.        ],
       [ 0.63      ,  0.37      ],
       [ 0.        ,  1.        ],
       [ 0.035     ,  0.965     ],
       [ 0.96038095,  0.03961905],
       [ 0.33      ,  0.67      ],
       [ 0.29      ,  0.71      ],
       [ 0.86      ,  0.14      ],
       [ 0.49      ,  0.51      ],
       [ 0.22      ,  0.78      ],
       [ 0.02      ,  0.98      ],
       [ 0.44      ,  0.56      ],
       [ 0.05      ,  0.95      ],
       [ 1.        ,  0.        ],
       [ 0.        ,  1.        ],
       [ 0.37      ,  0.63      ],
       [ 0.355     ,

In [199]:
survived = []
for pred in test_pred:
    if pred[0] >= pred[1]:
        survived.append(0)
    else:
        survived.append(1)
len(survived)

418

In [200]:
survived = np.asanyarray(survived)
ans = pd.DataFrame(data = p_ids)
ans["Survived"] = survived
ans.to_csv("rfmodel7.csv",index=False)